### ISSUE TITLE
Unable to show Image

### ISSUE THREAD

**Issue by sushi-developer** [ibrahemesam/repo-view#4]
It shows up like this when I add a picture to Readme.
![brave_IVGpNNLQip](https://github.com/ibrahemesam/repo-view/assets/78013257/7311b8ab-be3b-401c-800a-9b4fe58e124e)

**Comment by sushi-developer** [comment]
I tried add image using external link from pinterest and it's work just fine
![brave_Or7SnoTR0X](https://github.com/ibrahemesam/repo-view/assets/78013257/fd0439f2-c169-4a63-8006-a9acd146aa72)
![brave_ELPNIaQFhc](https://github.com/ibrahemesam/repo-view/assets/78013257/f98648fc-bf7d-4d86-b3a6-5b7584350254)

**Comment by ibrahemesam** [comment]
related https://github.com/ibrahemesam/repo-view/issues/9#issuecomment-2439700369

**Comment by ibrahemesam** [comment]
Fixed now
