### ISSUE TITLE
Proposal: Create a Download Button

### ISSUE THREAD

**Issue by mzaini30** [ibrahemesam/repo-view#6]
Here, I only see a Clone button. Could you create a Download button? Because the people who will visit my private repository are not programmers. They will definitely look for a download button.

**Comment by ibrahemesam** [comment]
Ok, I'll create it on 2 / June.
I'm very busy these days (due to university final exams).

**Comment by ibrahemesam** [comment]
- [x] add repo download btn
- [x] add current_file download btn

**Comment by ibrahemesam** [comment]
@mzaini30,
All done. If you need anything else, please let me know.
Otherwise, close [this issue](https://github.com/ibrahemesam/repo-view/issues/6).

**Comment by mzaini30** [comment]
Wow, thank you very much, sir. Sorry, I can't help with the pull request yet.
