### ISSUE TITLE
.R files do not display or download

### ISSUE THREAD

**Issue by lowestprime** [ibrahemesam/repo-view#8]
Contents of .R files in RepoView version of repo do not display.

https://ibrahemesam.github.io/repo-view/?token=6768705f676d656e686e4e4b524543686b4c3771434b367664476e51444a4461437a32704f615039_enc&owner=lowestprime&repo=BP-DNAm&path=Sandbox.R

![image](https://github.com/user-attachments/assets/008a4463-8f24-4a5a-b10d-6c41cb53248f)
![image](https://github.com/user-attachments/assets/74045a88-a96c-4e7c-81d7-4ecf8742d29b)

**Comment by ibrahemesam** [comment]
ok, I'll fix it after a week from now

**Comment by lowestprime** [comment]
> ok, I'll fix it after a week from now 

Thank you!

**Comment by ibrahemesam** [comment]
> FIXED<br>
![image](https://github.com/user-attachments/assets/36769e50-e115-4c6d-be98-b317918b6c96)
please revoke the github_token of your URL (for your security)<br>

thank you for reporting this issue<br>
it was not related to R language, the file extension in UPPER cased that issue.<br>
anyway, it's now fixed. have a good day :D
