### ISSUE TITLE
SVG and ipynb support?

### ISSUE THREAD

**Issue by lowestprime** [ibrahemesam/repo-view#9]
Is it possible to display .svg (in readme and repo browser preview) and .ipynb (in repo browser preview) as they do on GitHub?

![image](https://github.com/user-attachments/assets/b6f9e7b0-9c46-498a-8d3c-8a6e590d5734)

![image](https://github.com/user-attachments/assets/75882c47-c293-4522-b57d-659360bdda36)

![image](https://github.com/user-attachments/assets/1c1595e3-8b74-4726-8cc3-e5779584a92e)

**Comment by ibrahemesam** [comment]
Hello, @lowestprime.
Thank you for reporting this issue.
Sorry for late response. I've just seen this issue. I'll fix it as soon as possible.

**Comment by ibrahemesam** [comment]
- [x]  SVG
- [x] ipynb

**Comment by ibrahemesam** [comment]
@lowestprime ,
All done. If you need anything else, please let me know.
Otherwise, close [this issue](https://github.com/ibrahemesam/repo-view/issues/9).

**Comment by lowestprime** [comment]
Thanks, the only remaining display error is for the svgs in the readme.

RepoView:
![2024-10-03 12_09_17-lowestprime _ BP-DNAm · RepoView and 20 more pages - Personal - Microsoft​ Edge ](https://github.com/user-attachments/assets/4bbed958-eb39-4ee6-aa16-64998adb1680)

GitFront:
![2024-10-07 15_35_27-BP-DNAm · GitFront and 20 more pages - Personal - Microsoft​ Edge Canary](https://github.com/user-attachments/assets/501ab998-ca81-478d-90ae-449613d48977)

GitHub:
![2024-10-03 12_09_37-lowestprime_BP-DNAm and 20 more pages - Personal - Microsoft​ Edge Canary](https://github.com/user-attachments/assets/8c97997d-d0d5-46b6-87e7-1e43b5c1834b)

**Comment by ibrahemesam** [comment]
I'm aware of this issue. I'll fix it as soon as I can.
by the way, it's not just the SVG files in README
all Files with a relative path (to the repo) can't be fetched (yet)
even Files with absolute URL to another repo (but not accessible ie: private repo) wont be fetched as well

**Comment by ibrahemesam** [comment]
related https://github.com/ibrahemesam/repo-view/issues/4

**Comment by ibrahemesam** [comment]
<strong>TODO</strong>:
- [x] \<a\> href relative
- [x] \<a\> href absolute
- [x] \<img\> src relative
- [x] \<img\> src absolute
- [x] md link relative
- [x] md link absolute
- [x] md image relative
- [x] md image absolute

**Comment by ibrahemesam** [comment]
@lowestprime ,
All done. If you need anything else, please let me know.
& thanks for reporting bugs :D
